In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('IMDB_Dataset.csv')

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
#Lowecase

In [4]:
df['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [5]:
df['review'] = df['review'].str.lower()

In [5]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [ ]:
# Remove Html tag

In [7]:
import re 

def remove_html_tag(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'',text)

In [8]:
df['review']= df['review'].apply(remove_html_tag)

In [9]:
df['review'][2]

'I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). While some may be disappointed when they realize this is not Match Point 2: Risk Addiction, I thought it was proof that Woody Allen is still fully in control of the style many of us have grown to love.This was the most I\'d laughed at one of Woody\'s comedies in years (dare I say a decade?). While I\'ve never been impressed with Scarlet Johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.This may not be the crown jewel of his career, but it was wittier than "Devil Wears Prada" and more interesting than "Superman" a great comedy to go see with friends.'

In [ ]:
# Remove URL

In [10]:
def remove_url(text):
    pattern = re.compile('https?://\S+|www\.\S+')
    return pattern.sub(r'',text)

In [11]:
df['review'] = df['review'].apply(remove_url)
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. The filming tec...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [ ]:
# Remove punctuation

In [12]:
import string
import time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [13]:
exclude = string.punctuation

In [14]:
def remove_punctuation(text):
    for char in exclude:
        text = text.replace(char,'')
    return text

In [15]:
text = "I am bajarang dhamanekar!?"

In [16]:
start = time.time()
remove_punctuation(text)
time2 = time.time()-start
print(time2*50000)

0.0

In [17]:
def remove_punc(text):
    return text.translate(str.maketrans('','',exclude))

In [18]:
df.shape

(50000, 2)

In [19]:
start = time.time()
remove_punc(text)
time2 = time.time()-start
print(time2*50000)

0.0

In [20]:
df['review'] = df['review'].apply(remove_punctuation)
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production The filming tech...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically theres a family where a little boy J...  negative
4      Petter Matteis Love in the Time of Money is a ...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot bad dialogue bad acting idiotic direc...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  Im going to have to disagree with the previous...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [ ]:
#Chat Treatment

In [ ]:
chat_words= ""

In [ ]:
def chat_conversion(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)

    return " " .join(new_text)

In [ ]:
#Spell Mistake

In [21]:
from textblob import TextBlob

In [ ]:
incorrect_text = 'india is lagest democrocy country in the world'

textBlb = TextBlob(incorrect_text)
textBlb.correct().string

'india is largest democracy country in the world'

In [ ]:
# Remove Stopword

In [23]:
from nltk.corpus import stopwords

In [24]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [25]:
def remove_stopwords(text):
    new_text = []

    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return ' '.join(x)

In [26]:
remove_stopwords("one of the other reviewers has mentioned that ")

'one    reviewers  mentioned '

In [ ]:
# Remove Emoji

In [27]:
import re

def remove_emoji(text):
    emoji_pattern = re.compile(
        "["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map
        u"\U0001F1E0-\U0001F1FF"  # flags
        u"\U00002700-\U000027BF"  # dingbats
        u"\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE
    )
    return emoji_pattern.sub(r'', text)

In [28]:
text = "Hello 😊🚀! This is a test 👍🔥"
clean_text = remove_emoji(text)

print(clean_text)

Hello ! This is a test

In [29]:
!pip install emoji

Requirement already satisfied: emoji in c:\users\urp20\appdata\local\programs\python\python311\lib\site-packages (2.15.0)

WARNING: Ignoring invalid distribution ~rotobuf (C:\Users\urp20\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\urp20\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~rotobuf (C:\Users\urp20\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\urp20\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~rotobuf (C:\Users\urp20\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\urp20\AppData\Local\Programs\Python\Python311\Lib\site-packages)

[notice] A new release of pip is available: 25.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [30]:
import emoji
print(emoji.demojize("Ram is 😊"))

Ram is :smiling_face_with_smiling_eyes:

In [ ]:
#Tokenization

In [ ]:
#1 Using Split Function

In [31]:
sent1 = "Delhi is the capital of India"
sent1.split()

['Delhi', 'is', 'the', 'capital', 'of', 'India']

In [32]:
sent2 = "Mumbai is the financial hub of India. I want to go Mumbai"
sent2.split(".")

['Mumbai is the financial hub of India', ' I want to go Mumbai']

In [ ]:
#2 Regular Expression

In [33]:
import re
sent3 = " Banglore city is the IT hub of India. IT employee"
token = re.findall(r'\b\w+\b',sent3)
token

['Banglore', 'city', 'is', 'the', 'IT', 'hub', 'of', 'India', 'IT', 'employee']

In [34]:
text = """"Python is high level programming language.
It is the interpreted language.
It is the portable language.
It is object oriented programing Language"""


sentences = re.compile('[,!?]').split(text)
sentences

['"Python is high level programming language.\nIt is the interpreted language.\nIt is the portable language.\nIt is object oriented programing Language']

In [ ]:
#3 NLTK

In [35]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [36]:
sent5 = 'I have a Ph.D in A.I'
sent6 = " we're here to help! mail us at nk183@gmail.com"
sent7 = "A 5 km ride cost $10.50"

In [37]:
token1 = word_tokenize(sent5)
token1

['I', 'have', 'a', 'Ph.D', 'in', 'A.I']

In [38]:
token3 = word_tokenize(sent6)
token3

['we',
 "'re",
 'here',
 'to',
 'help',
 '!',
 'mail',
 'us',
 'at',
 'nk183',
 '@',
 'gmail.com']

In [39]:
token4 = word_tokenize(sent7)
token4

['A', '5', 'km', 'ride', 'cost', '$', '10.50']

In [41]:
token2 = sent_tokenize(text)
token2

['"Python is high level programming language.',
 'It is the interpreted language.',
 'It is the portable language.',
 'It is object oriented programing Language']

In [42]:
#4 Spacy

In [44]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
     -- ------------------------------------- 0.8/12.8 MB 3.0 MB/s eta 0:00:04
     ---- ----------------------------------- 1.6/12.8 MB 3.1 MB/s eta 0:00:04
     ------ --------------------------------- 2.1/12.8 MB 2.9 MB/s eta 0:00:04
     -------- ------------------------------- 2.6/12.8 MB 3.0 MB/s eta 0:00:04
     ---------- ----------------------------- 3.4/12.8 MB 3.2 MB/s eta 0:00:03
     ----------- ---------------------------- 3.7/12.8 MB 3.2 MB/s eta 0:00:03
     -------------- ------------------------- 4.7/12.8 MB 3.2 MB/s eta 0:00:03
     ----------------- ---------------------- 5.5/12.8 MB 3.2 MB/s eta 0:00:03
     ------------------ --------------------- 6.0/12.8 MB 3.2 MB/s eta 0:00:03
     --------------------- ------------------ 6.8/12.8 MB 3.3 MB/s eta 0:00:02
     ---------------------- ----------------- 7.1/12.8 MB 3.1 MB/s eta 0:00:02
     ------------------------ --------------- 7.9/12.8 MB 3.1 MB/s eta 0:00:02
     -------------------------- ------------- 8.4/12.8 MB 3.1 MB/s eta 0:00:02
     --------------------------- ------------ 8.9/12.8 MB 3.1 MB/s eta 0:00:02
     ------------------------------ --------- 9.7/12.8 MB 3.1 MB/s eta 0:00:01
     ------------------------------- -------- 10.2/12.8 MB 3.1 MB/s eta 0:00:01
     ---------------------------------- ----- 11.0/12.8 MB 3.1 MB/s eta 0:00:01
     ------------------------------------ --- 11.5/12.8 MB 3.1 MB/s eta 0:00:01
     ------------------------------------- -- 12.1/12.8 MB 3.1 MB/s eta 0:00:01
     ---------------------------------------  12.6/12.8 MB 3.0 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 3.0 MB/s eta 0:00:00
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

WARNING: Ignoring invalid distribution ~rotobuf (c:\Users\urp20\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (c:\Users\urp20\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~rotobuf (c:\Users\urp20\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (c:\Users\urp20\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~rotobuf (c:\Users\urp20\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (c:\Users\urp20\AppData\Local\Programs\Python\Python311\Lib\site-packages)

[notice] A new release of pip is available: 25.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [45]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [46]:
doc1 = nlp(sent5)
doc2 = nlp(sent6)
doc3 = nlp(sent7)

In [ ]:
# Stemming

In [47]:
from nltk.stem.porter import PorterStemmer

In [48]:
ps = PorterStemmer()
def stem_words(text):
    return " ".join(ps.stem(word) for word in text.split())

In [49]:
sample = "walks walking walked walk"
stem_words(sample)

'walk walk walk walk'

In [50]:
stem_words(text)

'"python is high level program language. it is the interpret language. it is the portabl language. it is object orient program languag'

In [ ]:
# Lemmatization

In [51]:
from nltk.stem import WordNetLemmatizer
import nltk

wordnet_lemmatizer = WordNetLemmatizer()

sentence = " He is going to shopping because purchasing some product which is very helpful for life"
punctuation = "):!.,;"

sentence_words = nltk.word_tokenize(sentence)

for word in sentence_words:
    if word in punctuation:
        sentence_words.remove(word)


sentence_words

print("{0:20}{1:20}".format("Word","Lemma"))
for word in sentence_words:
    print("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word,pos = 'v')))

Word                Lemma
He                  He
is                  be
going               go
to                  to
shopping            shop
because             because
purchasing          purchase
some                some
product             product
which               which
is                  be
very                very
helpful             helpful
for                 for
life                life